# Generated by Django 3.1.2 on 2020-10-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('key_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'Keys',
               
            },
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
